In [ ]:
import pandas as pd

In [ ]:
data=pd.read_json('/News_Category_Dataset_v3.json',lines=True)

In [ ]:
data=data['short_description'].head(20000)

In [ ]:
data.isnull().sum()

np.int64(0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
data.duplicated().sum()

np.int64(66)

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
tokenizer=Tokenizer(oov_token='<OOV>')

In [ ]:
tokenizer.fit_on_texts(data)

In [ ]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'for': 8,
 'is': 9,
 'on': 10,
 'said': 11,
 'that': 12,
 'was': 13,
 'with': 14,
 'his': 15,
 'it': 16,
 'at': 17,
 'he': 18,
 'are': 19,
 'as': 20,
 'has': 21,
 'have': 22,
 'an': 23,
 'from': 24,
 'be': 25,
 'president': 26,
 'this': 27,
 'trump': 28,
 '”': 29,
 'about': 30,
 'by': 31,
 'her': 32,
 'new': 33,
 'not': 34,
 'but': 35,
 'after': 36,
 'you': 37,
 'who': 38,
 'i': 39,
 'will': 40,
 'one': 41,
 'people': 42,
 'more': 43,
 'their': 44,
 'been': 45,
 'year': 46,
 'out': 47,
 'former': 48,
 'they': 49,
 'up': 50,
 'she': 51,
 'u': 52,
 'were': 53,
 's': 54,
 'all': 55,
 'we': 56,
 'just': 57,
 'what': 58,
 'first': 59,
 'over': 60,
 'had': 61,
 'house': 62,
 'than': 63,
 'says': 64,
 'when': 65,
 'two': 66,
 'no': 67,
 'would': 68,
 'or': 69,
 'some': 70,
 'like': 71,
 'state': 72,
 "it's": 73,
 'into': 74,
 'show': 75,
 'if': 76,
 'also': 77,
 'time': 78,
 'say': 79,
 'last': 80,
 'your': 81,
 'could

In [ ]:
len(tokenizer.word_index)

26343

In [ ]:
data=tokenizer.texts_to_sequences(data)

In [ ]:
data

[[163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13517,
  198,
  4125,
  5,
  2,
  33,
  13518,
  2,
  52,
  54,
  1298,
  8,
  2,
  897],
 [18,
  13,
  13519,
  31,
  2072,
  6,
  2540,
  65,
  18,
  2169,
  3,
  2,
  107,
  5,
  2,
  3038,
  36,
  2,
  4126,
  231,
  3,
  2,
  52,
  54,
  9667,
  247,
  7,
  973,
  1037],
 [507, 37, 22, 4, 1339, 37, 192, 1515, 58, 82, 25, 7729],
 [4127,
  258,
  3534,
  50,
  9668,
  10,
  93,
  13520,
  13521,
  6,
  18,
  9669,
  71,
  39,
  13,
  3829,
  15,
  3277,
  14,
  4,
  1064,
  13522,
  9670,
  7,
  13523,
  7730],
 [2073,
  2709,
  133,
  4496,
  1516,
  5027,
  13524,
  5,
  7731,
  2541,
  32,
  6,
  9671,
  32,
  4,
  747,
  36,
  196,
  5,
  2,
  1261,
  801,
  2397,
  338,
  784],
 [2,
  3830,
  46,
  94,
  191,
  13,
  591,
  402,
  17,
  2,
  403,
  1064,
  1517,
  10,
  637,
  51,
  13,
  199,
  418,
  307,
  36,
  32,
  186,
  353,
  32,
  898,
  392,
  11],
 [1183,
  12,


In [ ]:
input_sequences=[]
for seq in data:
    if len(seq)<2:
        continue
    for i in range(1,len(seq)):
        ngram=seq[:i+1]
        input_sequences.append(ngram)

In [ ]:
input_sequences

[[163, 352],
 [163, 352, 11],
 [163, 352, 11, 16],
 [163, 352, 11, 16, 9],
 [163, 352, 11, 16, 9, 162],
 [163, 352, 11, 16, 9, 162, 544],
 [163, 352, 11, 16, 9, 162, 544, 3],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396, 50],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396, 50, 14],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396, 50, 14, 2],
 [163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13517],
 [163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13517,
  198],
 [163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13

In [ ]:
max_len=max([len(i) for i in input_sequences])

In [ ]:
max_len

44

In [ ]:
input=pad_sequences(input_sequences,padding='pre',maxlen=max_len)

In [ ]:
input

array([[   0,    0,    0, ...,    0,  163,  352],
       [   0,    0,    0, ...,  163,  352,   11],
       [   0,    0,    0, ...,  352,   11,   16],
       ...,
       [   0,    0,    0, ...,   10, 3812,  559],
       [   0,    0,    0, ..., 3812,  559,  354],
       [   0,    0,    0, ...,  559,  354,   12]], dtype=int32)

In [ ]:
input[50]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,    18,    13, 13519,    31,  2072,     6,
        2540,    65,    18,  2169,     3,     2,   107,     5,     2,
        3038,    36,     2,  4126,   231,     3,     2,    52],
      dtype=int32)

In [ ]:
X=input[:,:-1]
y=input[:,-1]

In [ ]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 163], dtype=int32)

In [ ]:
y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(240011, 43)

In [ ]:
vocab_size=len(tokenizer.word_index)+1

In [ ]:
vocab_size

26344

In [ ]:
max_len=X.shape[1]

In [ ]:
model=Sequential([Embedding(vocab_size,128,input_length=max_len),LSTM(256),Dense(vocab_size,activation='softmax')])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.build(input_shape=(None,max_len))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 43, 128)        │     3,372,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 26344)          │     6,770,408 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,536,680 (40.19 MB)

 Trainable params: 10,536,680 (40.19 MB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.fit(X_train,y_train,epochs=30,validation_data=(X_test,y_test))

Epoch 1/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 126s 17ms/step - accuracy: 0.5305 - loss: 2.3190 - val_accuracy: 0.1130 - val_loss: 8.3689
Epoch 2/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 123s 16ms/step - accuracy: 0.5675 - loss: 2.1080 - val_accuracy: 0.1112 - val_loss: 8.5608
Epoch 3/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 121s 16ms/step - accuracy: 0.5999 - loss: 1.9352 - val_accuracy: 0.1063 - val_loss: 8.7585
Epoch 4/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 120s 16ms/step - accuracy: 0.6270 - loss: 1.7852 - val_accuracy: 0.1090 - val_loss: 8.9544
Epoch 5/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 119s 16ms/step - accuracy: 0.6507 - loss: 1.6618 - val_accuracy: 0.1063 - val_loss: 9.1270
Epoch 6/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 119s 16ms/step - accuracy: 0.6707 - loss: 1.5540 - val_accuracy: 0.1026 - val_loss: 9.3060
Epoch 7/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 121s 16ms/step - accuracy: 0.6884 - loss: 1.4604 - val_accuracy: 0.1009 - val_loss: 9.4708
Epoch 8/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 119s 16ms/step - accuracy: 

In [45]:
model.save('Next_Word_model_1.h5')

In [46]:
import pickle
with open('tokenizer_1.pk1','wb') as file:
    pickle.dump(tokenizer,file)